---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: sort-simple-yaml
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--format", "requirements.txt", "--output", "requirements.txt"]
