on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: beets-alpine-exec
          include-v-in-tag: false
          skip-labeling: true
          token: ${{ secrets.GITHUB_TOKEN }}
